---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace }}
  name: ingress-2048
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    {{- if .Values.ingress.certificateArn | ne "" }}
    alb.ingress.kubernetes.io/certificate-arn: {{.Values.ingress.certificateArn}}
    {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: service-2048
              servicePort: 80
